name: Android Test

on: pull_request

jobs:
  android_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Echo ANDROID_HOME
        run: |
          echo $ANDROID_HOME
      - name: ls $ANDROID_HOME/tools/bin
        run: |
          ls $ANDROID_HOME/tools/bin
      - name: ls $ANDROID_HOME/emulator
        run: |
          ls $ANDROID_HOME/emulator
      - name: List up AVDs
        run: |
          $ANDROID_HOME/emulator/emulator -list-avds